### PR TITLE
Fixes tooltip issue

### LINKED ISSUE #381: Getting odd tooltips in grunt-ts
I'm currently working on grunt-ts support for TypeScript 1.5 in the update-to-typescript-1.5.0-beta branch.

I'm getting some very odd tooltips in atom-typescript.  Any ideas?  Am I doing something wrong here?

I have atom-typescript 4.5.7.  These screenshots were both taken while compile.ts was open.

unusualtooltips1

unusualtooltips2

### PR DESCRIPTION
**Pull request by nycdotnet**
This fixes #381 .

### CODE REVIEW

File: lib/main/atom/tooltipManager.ts [hunk 1]
```diff
@@ -74,6 +74,8 @@ export function attach(editorView: JQuery, editor: AtomCore.IEditor) {
         if (exprTypeTooltip) return;
 
         var pixelPt = pixelPositionFromMouseEvent(editorView, e);
+        pixelPt.top += editor.displayBuffer.getScrollTop();
+        pixelPt.left += editor.displayBuffer.getScrollLeft();
         var screenPt = editor.screenPositionForPixelPosition(pixelPt);
```
Comment (basarat) [inline lib/main/atom/tooltipManager.ts]: Maybe move this logic *into* `pixelPositionFromMouseEvent`. I think just remove the -left/top here : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/tooltipManager.ts#L140-L141

**Comment by david-driscoll** [comment]
FYI thanks for the fix, this worked us @ omnisharp too! :+1:
